kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 8384
    targetPort: 8384
    name: {{ .Values.appName }}-web
  - port: 22000
    targetPort: 22000
    name: {{ .Values.appName }}-lis
  selector:
    k8s-app: {{ .Values.appName }}
