apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.appName }}
    spec:
      nodeSelector:
        {{ .Values.selector.key }}: "{{ .Values.selector.value }}"
      volumes:
      - name: {{ .Values.appName }}
        persistentVolumeClaim:
          claimName: {{ .Values.appName }}
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          ports:
          - name: {{ .Values.appName }}-web
            containerPort: 8384
          - name: {{ .Values.appName }}-lis
            containerPort: 22000
          volumeMounts:
          - mountPath: /config
            name: {{ .Values.appName }}
            subPath: config
          - mountPath: /storage
            name: {{ .Values.appName }}
            subPath: data
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: Europe/Madrid
          # - name: UMASK_SET
          #   value: "022"
