apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}
type: Opaque
stringData:
  mariadb-root-pass: {{ .Values.mariadb-root-pass }}
  seafile-user: {{ .Valeus.seafile-user }}
  seafile-pass: {{ .Valeus.seafile-pass }}
