apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}
type: Opaque
stringData:
  mariadbrootpass: {{ .Values.mariadbrootpass }}
  seafileuser: {{ .Valeus.seafileuser }}
  seafilepass: {{ .Valeus.seafilepass }}
