apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}
type: Opaque
stringData:
  mariadbrootpass: {{ .Values.mariadbrootpass }}
  seafileuser: {{ .Values.seafileuser }}
  seafilepass: {{ .Values.seafilepass }}
