apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.appName }}
    spec:
      nodeSelector:
        {{ .Values.selector.key }}: "{{ .Values.selector.value }}"
      volumes:
      - name: {{ .Values.appName }}
        persistentVolumeClaim:
          claimName: {{ .Values.appName }}
      containers:
        # MariaDB
        - name: {{ .Values.appName }}-mariadb
          image: "{{ .Values.image.mariadb }}:{{ .Values.image.mariadbTag }}"
          ports:
            - name: mariadb
              containerPort: 3306
          env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appName }}
                key: mariadbrootpass
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: {{ .Values.appName }}
            subPath: mariadb/mysql
          - mountPath: /etc/mysql/conf.d
            name: {{ .Values.appName }}
            subPath: mariadb/conf.d
          - mountPath: /var/lib/backup
            name: {{ .Values.appName }}
            subPath: mariadb/backup
        # seafile
        - name: {{ .Values.appName }}-seafile
          image: "{{ .Values.image.seafile }}:{{ .Values.image.seafileTag }}"
          ports:
          - name: seafile
            containerPort: 80
          env:
          - name: DB_HOST
            value: {{ .Values.appName }}
          - name: SEAFILE_ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appName }}
                key: seafileuser
          - name: SEAFILE_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appName }}
                key: seafilepass
          - name: DB_ROOT_PASSWD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appName }}
                key: mariadbrootpass
          volumeMounts:
          - mountPath: /shared
            name: {{ .Values.appName }}
            subPath: seafile
