apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: nextcloud-v
        persistentVolumeClaim:
          claimName: {{ .Values.volume.pvcName }}
      containers:
        - name: "mariadb"
          image: "{{ .Values.image.mariadb }}:{{ .Values.image.mariadbTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3306
              protocol: TCP
          env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: {{ .Values.secret.mariadbRootPasswordKey }}
          - name: MARIADB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: {{ .Values.secret.mariadbUsernameKey }}
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: {{ .Values.secret.mariadbPasswordKey }}
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: {{ .Values.secret.mariadbDatabaseKey }}
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: nextcloud-v
            subPath: nextcloud/mariadb/mysql
          - mountPath: /etc/mysql/conf.d
            name: nextcloud-v
            subPath: nextcloud/mariadb/conf.d
          - mountPath: /var/lib/backup
            name: nextcloud-v
            subPath: nextcloud/mariadb/backup
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: "nextcloud"
          image: "{{ .Values.image.nextcloud }}:{{ .Values.image.nextcloudTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - mountPath: /var/www/html
            name: nextcloud-v
            subPath: nextcloud/nextcloud
