apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.appName }}
  labels:
    k8s-app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.appName }}
    spec:
      volumes:
      - name: nextcloud-v
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName }}
      containers:
        - name: "mariadb"
          image: "{{ .Values.image.mariadb }}:{{ .Values.image.mariadbTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mariadb
              containerPort: 3306
          env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: {{ .Values.secret.mariadbRootPasswordKey }}
          - name: MARIADB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: {{ .Values.secret.mariadbUsernameKey }}
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: {{ .Values.secret.mariadbPasswordKey }}
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: {{ .Values.secret.mariadbDatabaseKey }}
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: nextcloud-v
            subPath: nextcloud/mariadb/mysql
          - mountPath: /etc/mysql/conf.d
            name: nextcloud-v
            subPath: nextcloud/mariadb/conf.d
          - mountPath: /var/lib/backup
            name: nextcloud-v
            subPath: nextcloud/mariadb/backup
        - name: "nextcloud"
          image: "{{ .Values.image.nextcloud }}:{{ .Values.image.nextcloudTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: nextcloud
              containerPort: 80
          volumeMounts:
          - mountPath: /var/www/html
            name: nextcloud-v
            subPath: nextcloud/nextcloud
