apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.appName }}
spec:
  schedule: "{{ .Values.cron }}"
  jobTemplate:
    spec:
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: nextcloud-cronjob
            image: "{{ .Values.image.nextcloud }}:{{ .Values.image.nextcloudTag }}"
            args:
            - su
            - -s
            - /bin/bash
            - -c
            - "php cron.php"
            - www-data
            volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-v
              subPath: nextcloud
          volumes:
          - name: nextcloud-v
            persistentVolumeClaim:
              claimName: {{ .Values.pvcName }}
