apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.appName }}
  labels:
    k8s-app: {{ .Values.appName }}
spec:
  schedule: "{{ .Values.cron }}"
  jobTemplate:
    spec:
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: nextcloud-cronjob
            image: hectormolinero/curl
            command: [ "curl" ]
            args:
            - "--fail"
            - "-L"
            - "http://{{ .Values.host }}/cron.php"
