apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: {{ .Values.secret.mariadbRootPassword }}
  MARIADB_USERNAME: {{ .Values.secret.mariadbUsername }}
  MARIADB_PASSWORD: {{ .Values.secret.mariadbPassword }}
  MARIADB_DATABASE: {{ .Values.secret.mariadbDatabase }}
