kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  ports:
  - port: 7777
    targetPort: 7777
    name: nextcloud
  - port: 3306
    targetPort: 3306
    name: mariadb
  selector:
    k8s-app: {{ .Values.appName }}
