kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: {{ include "chart.fullname" . }}
  name: {{ include "chart.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.nextcloudPort }}
    targetPort: 80
  - port: {{ .Values.service.mariadbPort }}
    targetPort: 3306
  selector:
    k8s-app: {{ include "chart.fullname" . }}
