apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.appName }}
    spec:
      nodeSelector:
        {{ .Values.selector.key }}: "{{ .Values.selector.value }}"
      volumes:
      - name: {{ .Values.appName }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName }}
      containers:
        - name: "{{ .Values.appName }}"
          image: "{{ .Values.image.firefoxsync }}:{{ .Values.image.firefoxsyncTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: {{ .Values.appName }}
            containerPort: 5000
          volumeMounts:
          - mountPath: /data
            name: {{ .Values.appName }}
            subPath: firefoxsync/
          env:
          - name: SYNCSERVER_PUBLIC_URL
            value: "http://{{ .Values.host }}/"
          - name: SYNCSERVER_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: {{ .Values.secret.key }}
          - name: SYNCSERVER_SQLURI
            value: "sqlite:////data/syncserver.db"
          - name: SYNCSERVER_BATCH_UPLOAD_ENABLED
            value: "true"
          - name: SYNCSERVER_FORCE_WSGI_ENVIRON
            value: "true"
          - name: SYNCSERVER_ALLOW_NEW_USER
            value: "true"
