appName: firefoxsync
namespace: default

replicaCount: 1

image:
  firefoxsync: mozilla/syncserver
  firefoxsyncTag: latest
  pullPolicy: IfNotPresent

pvcName:

secret:
  name:
  key:

host:

selector:
  key:
  value:
