apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: changeip-cronjob
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.cron }}
  jobTemplate:
    spec:
      template:
        spec:
          successfulJobsHistoryLimit: 1
          failedJobsHistoryLimit: 2
          restartPolicy: Never
          containers:
          - name: changeip-image
            image: arnaubennassar/changeip-updater
            env:
            - name: CHANGEIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: changeip-secret-{{ .Values.namespace }}
                  key: user
            - name: CHANGEIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: changeip-secret-{{ .Values.namespace }}
                  key: pass
            - name: CHANGEIP_RECORD
              valueFrom:
                secretKeyRef:
                  name: changeip-secret-{{ .Values.namespace }}
                  key: record
