apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.host.transmission }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.appName }}
          servicePort: 9091
  - host: {{ .Values.host.sonarr }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.appName }}
          servicePort: 8989
  - host: {{ .Values.host.radarr }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.appName }}
          servicePort: 7878
  # - host: {{ .Values.host.bazarr }}
  #   http:
  #     paths:
  #     - path: /
  #       backend:
  #         serviceName: {{ .Values.appName }}
  #         servicePort: 6767
  - host: {{ .Values.host.jackett }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.appName }}
          servicePort: 9117
  # - host: {{ .Values.host.jellyfin }}
  #   http:
  #     paths:
  #     - path: /
  #       backend:
  #         serviceName: {{ .Values.appName }}
  #         servicePort: 8096
  # - host: {{ .Values.host.plex }}
  #   http:
  #     paths:
  #     - path: /
  #       backend:
  #         serviceName: {{ .Values.appName }}
  #         servicePort: 32400
