apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
      - {{ .Values.host.transmission }}
      - {{ .Values.host.sonarr }}
      - {{ .Values.host.radarr }}
      - {{ .Values.host.jackett }}
      secretName: "{{ .Values.appName }}-cert"
  rules:
  - host: {{ .Values.host.transmission }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.appName }}
          servicePort: 9091
  - host: {{ .Values.host.sonarr }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.appName }}
          servicePort: 8989
  - host: {{ .Values.host.radarr }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.appName }}
          servicePort: 7878
  # - host: {{ .Values.host.bazarr }}
  #   http:
  #     paths:
  #     - path: /
  #       backend:
  #         serviceName: {{ .Values.appName }}
  #         servicePort: 6767
  - host: {{ .Values.host.jackett }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.appName }}
          servicePort: 9117
