kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 9091
    targetPort: 9091
    name: transmission
  - port: 8989
    targetPort: 8989
    name: sonarr
  - port: 7878
    targetPort: 7878
    name: radarr
  # - port: 6767
  #   targetPort: 6767
  #   name: bazarr
  - port: 9117
    targetPort: 9117
    name: jackett
  # - port: 8096
  #   targetPort: 8096
  #   name: jellyfin
  - port: 32400
    targetPort: 32400
    name: plex
  selector:
    k8s-app: {{ .Values.appName }}
