apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.appName }}
    spec:
      nodeSelector:
        {{ .Values.selector.key }}: "{{ .Values.selector.value }}"
      volumes:
      - name: piflix-v
        persistentVolumeClaim:
          claimName: {{ .Values.appName }}
      containers:
# PLEX
        - name: "plex"
          image: "{{ .Values.image.plex }}:{{ .Values.image.plexTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: {{ .Values.appName }}
            containerPort: 32400
          volumeMounts:
          - mountPath: /config
            name: piflix-v
            subPath: piflix/plex/config
          - mountPath: /transcode
            name: piflix-v
            subPath: piflix/plex/transcode
          - mountPath: /data/movies
            name: piflix-v
            subPath: piflix/data/movies
          - mountPath: /data/tvshows
            name: piflix-v
            subPath: piflix/data/series
          - mountPath: /data/fotos
            name: piflix-v
            subPath: piflix/data/fotos
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: Europe/Madrid
