apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.appName }}
  namespace: default
spec:
  entryPoints:
    - web
    # - websecure
  routes:
    - match: Host(`{{ .Values.host }}`)
      kind: Rule
      services:
        - name: {{ .Values.appName }}
          port: 32400
  #     middlewares:
  #       - name: https-only
  # tls:
  #   certResolver: default
