apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: {{ .Values.appName }}
      port: 32400
  selector:
    k8s-app: {{ .Values.appName }}
