kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 32400
    targetPort: 32400
    name: {{ .Values.appName }}
  selector:
    k8s-app: {{ .Values.appName }}
