apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.volume.size }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: gluster
    path: gluVol
    readOnly: false
    type: "/v3/cluster/schemas/glusterfsVolumeSource"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  volumeName: {{ .Values.namespace }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}
