apiVersion: v1
appVersion: "0.1"
description: Traefik ingress controller, includes a cronjob to update chageip.com DDNS
name: traefik
version: 0.1.17
icon: https://cdn-images-1.medium.com/max/1600/1*5EE7y57XvUKdmfvA0pCkRQ.png
