apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}

spec:
  ports:
    - protocol: TCP
      name: web
      port: {{ .Values.ports.http }}
    - protocol: TCP
      name: {{ .Values.appName }}
      port: 8080
    - protocol: TCP
      name: websecure
      port: {{ .Values.ports.https }}
  selector:
    app: {{ .Values.appName }}
