apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: {{ .Values.namespace }}
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeName }}
      volumes:
      - name: traefik-cache
        persistentVolumeClaim:
          claimName: {{ .Values.appName }}
      containers:
        - name: traefik
          image: traefik:v2.0
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.Address=:{{ .Values.ports.http }}
            - --entrypoints.websecure.Address=:{{ .Values.ports.https }}
            - --providers.kubernetescrd
            - --certificatesresolvers.default.acme.tlschallenge
            - --certificatesresolvers.default.acme.email={{ .Values.email }}
            - --certificatesresolvers.default.acme.storage=/etc/traefik-cache/acme.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          volumeMounts:
          - mountPath: /etc/traefik-cache
            name: traefik-cache
            subPath: {{ .Values.volume.subPath }}
          ports:
            - name: web
              containerPort: {{ .Values.ports.http }}
            - name: websecure
              containerPort: {{ .Values.ports.https }}
            - name: {{ .Values.appName }}
              containerPort: 8080
