apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-only
spec:
  redirectScheme:
    scheme: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: htpaswd
spec:
  basicAuth:
    secret: traefik-htpaswd
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-htpaswd
type: Opaque
stringData: {{ .Values.htpaswd }}
