apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.appName }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.host }}`)
    kind: Rule
    services:
    - name: {{ .Values.appName }}
      port: 8080
