kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-https-cfg
  namespace: kube-system
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "INFO"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
    [acme]
      email = "{{ .Values.email }}"
      storage = "/etc/traefik/acme2.json"
      acmeLogging = true
      entryPoint = "https"
      OnHostRule = true
      # caServer = "https://acme-v01.api.letsencrypt.org/directory"
      [acme.httpChallenge]
        entryPoint="http"
    [file]
      [backends]
        [backends.backend1]
          [backends.backend1.servers]
            [backends.backend1.servers.server0]
              url = "https://192.168.1.12"

      [frontends]
        [frontends.frontend1]
          entryPoints = ["https"]
          backend = "backend1"
          passHostHeader = true
          [frontends.frontend1.routes]
            [frontends.frontend1.routes.route0]
              rule = "Host:www.rancher.nau.qhigh.com"
