kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeName }}
      volumes:
      - name: traefik-cache
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName }}
      containers:
        - name: traefik
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --api.dashboard=true
            - --providers.kubernetescrd
            - --certificatesresolvers.default.acme.tlschallenge
            - --certificatesresolvers.default.acme.email=4nau_acc@protonmail.com
            - --certificatesresolvers.default.acme.storage=/etc/traefik-cache/acme.json
          volumeMounts:
          - mountPath: /etc/traefik-cache
            name: traefik-cache
            subPath: traefik/cache
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: traefik
              containerPort: 8080
