apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  volumes:
  - name: traefik-cache
    persistentVolumeClaim:
      claimName: {{ .Values.pvcName }}
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeName }}
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0
          volumeMounts:
          - mountPath: /etc/traefik
            subPath: traefik/cache
            name: traefik-cache
          - mountPath: /config-files
            subPath: traefik/config
            name: traefik-cache
          args:
            - --api
            - --accesslog
            - --entrypoints.web.Address=:8888
            - --entrypoints.websecure.Address=:443
            - --providers.kubernetescrd
            - --certificatesresolvers.default.acme.tlschallenge
            - --certificatesresolvers.default.acme.email=foo@you.com
            - --certificatesresolvers.default.acme.storage=acme.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          ports:
          - name: web
            containerPort: 80
            hostPort: 80
          - name: websecure
            containerPort: 443
            hostPort: 443
          - name: admin
            containerPort: 8888
