apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ingress-controller-https
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/auth-type: basic
    traefik.ingress.kubernetes.io/auth-secret: generic-password
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik-ingress-controller-https
          servicePort: 80
