kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: traefik
  name: traefik
  namespace: default
spec:
  ports:
  - protocol: TCP
    name: traefik
    port: 8080
    targetPort: 8080
  selector:
    k8s-app: traefik
