kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: traefik-ingress-controller-https
  name: traefik-ingress-controller-https
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 8888
  selector:
    k8s-app: traefik-ingress-controller-https
