kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: traefik-ingress-controller-https
  name: traefik-ingress-controller-https
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    k8s-app: traefik-ingress-controller-https
