apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}
type: Opaque
stringData:
  key: {{ .Values.key }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
data:
  backup.list: {{ .Values.config }}
