apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}-to
spec:
  capacity:
    storage: {{ .Values.volumes.size }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: gluster
    path: gluVol/{{ .Values.appName }}
    readOnly: false
    type: "/v3/cluster/schemas/glusterfsVolumeSource"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-to
  namespace: {{ .Values.namespace }}
spec:
  volumeName: {{ .Values.appName }}-to
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.size }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}-from
spec:
  capacity:
    storage: {{ .Values.volumes.size }}
  accessModes:
  - ReadOnlyOnce
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: gluster
    path: gluVol/{{ .Values.volumes.from }}
    readOnly: true
    type: "/v3/cluster/schemas/glusterfsVolumeSource"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-from
  namespace: {{ .Values.namespace }}
spec:
  volumeName: {{ .Values.appName }}-from
  accessModes:
  - ReadOnlyOnce
