apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.appName }}
    spec:
      nodeSelector:
        {{ .Values.selector.key }}: "{{ .Values.selector.value }}"
      volumes:
      - name: {{ .Values.appName }}-data
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName }}
      containers:
        - name: "{{ .Values.appName }}"
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--syncmode=full", "--gcmode=archive", "--rinkeby"]
          ports:
          - name: api
            containerPort: 8545
          - name: p2p
            containerPort: 30303
          volumeMounts:
          - mountPath: /root
            name: {{ .Values.appName }}-data
            subPath: etherum/
