apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /disk/traefik/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-three
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-pvc
  namespace: kube-system
spec:
  volumeName: traefik-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
