appName: nextcloud
namespace: default

replicaCount: 1

image:
  nextcloud: nextcloud
  nextcloudTag: 15.0.7-apache
  mariadb: webhippie/mariadb
  mariadbTag: latest
  pullPolicy: IfNotPresent

secret:
  name:
  mariadbRootPasswordKey:
  mariadbUsernameKey:
  mariadbPasswordKey:
  mariadbDatabaseKey:

pvcName:

host: cloud.nau.qhigh.com

cron: "10 * * * *"
