replicaCount: 1

image:
  nextcloud: nextcloud
  nextcloudTag: 15.0.7-apache
  mariadb: webhippie/mariadb
  mariadbTag: latest
  pullPolicy: IfNotPresent

secret:
  # ENCODE VALUES IN base64 !!!!
    mariadbRootPassword:
    mariadbUsername:
    mariadbPassword:
    mariadbDatabase:

volume:
  pvcName:

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  nextcloudPort: 80                               # SHOULD BE SAME VARIABLE?
  mariadbPort: 3306

# ingress:
#   #
#   enabled: true
#   annotations:
#     kubernetes.io/ingress.class: traefik
#   hosts:
#     - host: cloud.nau.qhigh.com
#       paths:
#       - path: /
#         servicePort: 80                           # SHOULD BE SAME VARIABLE?
#
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local

cron:
  nextcloud: "10 * * * *"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
