apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.appName }}
    spec:
      nodeSelector:
        {{ .Values.selector.key }}: {{ .Values.selector.value }}
      volumes:
      - name: wordpress-v
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName }}
      containers:
        # MARIADB CONTAINER
        - name: "mariadb"
          image: "{{ .Values.image.mariadb }}:{{ .Values.image.mariadbTag }}"
          ports:
            - name: mariadb
              containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: {{ .Values.secret.mariadbRootPasswordKey }}
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: wordpress-v
            subPath: wordpress/mariadb
        # WORDPRESS CONTAINER
        - name: "wordpress"
          image: "{{ .Values.image.wordpress }}:{{ .Values.image.wordpressTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # volumeMounts:
          # - mountPath: /var/www/html
          #   name: wordpress-v
          #   subPath: wordpress/wordpress
          ports:
            - name: wordpress
              containerPort: 80
          env:
          - name: WORDPRESS_DB_HOST
            value: "wordpress"
          - name: WORDPRESS_DB_USER
            value: "root"
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: {{ .Values.secret.mariadbRootPasswordKey }}
          - name: WORDPRESS_DB_NAME
            value: "word"
          - name: WORDPRESS_TABLE_PREFIX
            value: "wp_"
          - name: WORDPRESS_CONFIG_EXTRA
            value: |
              /* Multisite */
              define('WP_ALLOW_MULTISITE', true );
              define('MULTISITE', true);
              define('SUBDOMAIN_INSTALL', false);
              define('DOMAIN_CURRENT_SITE', '{{ .Values.host }}');
              define('PATH_CURRENT_SITE', '/');
              define('SITE_ID_CURRENT_SITE', 1);
              define('BLOG_ID_CURRENT_SITE', 1);
