apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}
type: Opaque
stringData:
  key: {{ .Values.key }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
data:
  backup.list: |
    {{ .Values.config }}
