apiVersion: v1
appVersion: "1.0"
description: TLS/SSL certification bot to be used with nginx ingress controller
name: cert-manager
version: 0.0.2
icon: https://www.comodo.com/business-security/pki-management/certificate-management/images/certificate-management.png
